src/main/java/com/cvparse/admin/beans/ListProblemsBean.java
package com.cvparse.admin.beans;

import java.util.List;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import com.cvparse.ejb.ProblemEJB;
import com.cvparse.entity.Problem;

@ManagedBean
@RequestScoped
public class ListProblemsBean {
	private Logger logger = Logger.getLogger(this.getClass().getName());

	@EJB
	private ProblemEJB problemEjb;
	

	public List<Problem> getProblemList() {
		return problemEjb.loadAll();
	}
}

src/main/webapp/admin/listproblems.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

<ui:composition template="../index.xhtml">

	<ui:define name="innerbody">

		<h:dataTable styleClass="table"
			value="#{listProblemsBean.problemList}" var="pr">

			<h:column>
				<f:facet name="header">
					<h:outputText value="id" />
				</f:facet>
				<h:outputText value="#{pr.id}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="name" />
				</f:facet>
				<h:outputText value="#{pr.name}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="created" />
				</f:facet>
				<h:outputText value="#{pr.createDate}">
					<f:convertDateTime type="date" pattern="dd-MM-yyyy" />
				</h:outputText>
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="action" />
				</f:facet>
				<h:outputText value="edit" />
			</h:column>

		</h:dataTable>

	</ui:define>

</ui:composition>

</html>