src/main/java/com/cvparse/admin/beans/ListProblemsBean.java
package com.cvparse.admin.beans;

import java.util.List;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import com.cvparse.ejb.ProblemEJB;
import com.cvparse.entity.Problem;

@ManagedBean
@RequestScoped
public class ListProblemsBean {
	private Logger logger = Logger.getLogger(this.getClass().getName());

	@EJB
	private ProblemEJB problemEjb;
	

	public List<Problem> getProblemList() {
		return problemEjb.loadAll();
	}
}

src/main/java/com/cvparse/beans/CodeBean.java
package com.cvparse.beans;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import javax.faces.model.SelectItem;

import com.cvparse.ejb.ProblemSourceCodeEJB;
import com.cvparse.process.JavaCompileCommand;

@ManagedBean
@RequestScoped
public class CodeBean {
	private Logger logger = Logger.getLogger(this.getClass().getName());

	@EJB
	private ProblemSourceCodeEJB problemSourceCodeEjb;
	
	private String input;
	private String output;
	private String timer;
	private String currentLang;
	private List<SelectItem> langList = new ArrayList<SelectItem>();

	public void compileAction() {
		System.out.println("compileAction --> " + getUUID());
		long startTS = System.currentTimeMillis();
		JavaCompileCommand cmd = new JavaCompileCommand();
		try {
			String name = "Test"; //TODO change to problem.getName
			output = cmd.compile(getUUID(), name, input);
		} catch (IOException e) {
			logger.log(Level.SEVERE, "could not compile ", e);
		}
		timer = ""+ (System.currentTimeMillis() - startTS);
	}

	public void testAction() {
		long startTS = System.currentTimeMillis();
		logger.info("testAction --> " + getSessionId());
		timer = ""+ (System.currentTimeMillis() - startTS);
	}
	
	
	private String getSessionId() {
		FacesContext fCtx = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) fCtx.getExternalContext().getSession(false);
		return session.getId();
	}
	
	private String getUUID() {
		String session = getSessionId();
		final SimpleDateFormat sdf = new SimpleDateFormat("yyyy.MM.dd");
		return sdf.format(new Date()) + "-" + session.replaceAll(".undefined", "");
	}


	public String getTimer() {
		return timer;
	}

	public void setTimer(String timer) {
		this.timer = timer;
	}

	public String getOutput() {
		return output == null ? null : output.replace("\n", "<br />");
	}

	public void setOutput(String output) {
		this.output = output;
	}

	public String getCurrentLang() {
		return currentLang;
	}

	public void setCurrentLang(String currentLang) {
		this.currentLang = currentLang;
	}

	public List<SelectItem> getLangList() {
		if (langList == null || langList.size() == 0) { //TODO remove test data...
			langList.add(new SelectItem(problemSourceCodeEjb.load(1).getLanguage().toString()));
		}
		return langList;
	}

	public void setLangList(List<SelectItem> langList) {
		this.langList = langList;
	}

	public String getInput() {
		if (input == null) { //TODO remove test data...
			input = problemSourceCodeEjb.load(1).getBoilerplate();
		}
		
		return input;
	}

	public void setInput(String input) {
		this.input = input;
	}

}

src/main/java/com/cvparse/beans/HeaderBean.java
package com.cvparse.beans;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

@ManagedBean
@RequestScoped
public class HeaderBean {

	private final String active = "active";
	
	public String getHomeClass() {
		return "".equals(getProblemClass()) && "".equals(getSolutionClass()) 
				&& "".equals(getResourcesClass()) ? active : "";
	}
	public String getProblemClass() {
		return getRequestURL().indexOf("problem.jsf") == -1 ? "" : active;
	}
	public String getSolutionClass() {
		return getRequestURL().indexOf("code.jsf") == -1 ? "" : active;
	}
	public String getResourcesClass() {
		return getRequestURL().indexOf("resources.jsf") == -1 ? "" : active;
	}
	
	private String getRequestURL() {
		Object request = FacesContext.getCurrentInstance().getExternalContext().getRequest();
		if (request instanceof HttpServletRequest) {
			return ((HttpServletRequest) request).getRequestURL().toString();
		} else {
			return "";
		}
	}
}

src/main/java/com/cvparse/beans/HomeBean.java
package com.cvparse.beans;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

@ManagedBean
@RequestScoped
public class HomeBean {

	private final String active = "active";
	
	public String getWelcomeClass() {
		return "".equals(getSigninClass()) && "".equals(getAdminClass()) 
				&& "".equals(getJobsClass()) && "".equals(getPartnersClass()) 
				&& "".equals(getContactClass()) && "".equals(getAboutClass()) ? active : "";
	}
	public String getSigninClass() {
		return getRequestURL().indexOf("signin.jsf") == -1 ? "" : active;
	}
	public String getAdminClass() {
		return getRequestURL().indexOf("/admin/") == -1 ? "" : active;
	}
	public String getJobsClass() {
		return getRequestURL().indexOf("jobs.jsf") == -1 ? "" : active;
	}
	public String getPartnersClass() {
		return getRequestURL().indexOf("partners.jsf") == -1 ? "" : active;
	}
	public String getAboutClass() {
		return getRequestURL().indexOf("about.jsf") == -1 ? "" : active;
	}
	public String getContactClass() {
		return getRequestURL().indexOf("contact.jsf") == -1 ? "" : active;
	}
	
	private String getRequestURL() {
		Object request = FacesContext.getCurrentInstance().getExternalContext().getRequest();
		if (request instanceof HttpServletRequest) {
			return ((HttpServletRequest) request).getRequestURL().toString();
		} else {
			return "";
		}
	}
}

src/main/java/com/cvparse/beans/ProblemBean.java
package com.cvparse.beans;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

@RequestScoped
@ManagedBean
public class ProblemBean {

	private int id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public String getUrl() {
		return "http://en.wikipedia.org/wiki/Fibonacci_number";
	}
	
}

src/main/java/com/cvparse/beans/ResourcesBean.java
package com.cvparse.beans;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import com.cvparse.ejb.ProblemSourceCodeEJB;

@RequestScoped
@ManagedBean
public class ResourcesBean {

	@EJB
	private ProblemSourceCodeEJB problemSourceCodeEjb;

	private String testCode;

	public String getTestCode() {
		if (testCode == null) {
			testCode = problemSourceCodeEjb.load(1).getTestcode();
		}
		return testCode;
	}
	
}

src/main/java/com/cvparse/entity/FileUpload.java
/*
 * Copyright (c) 2013 Michael Bochenek 
 */
package com.cvparse.entity;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class FileUpload {

	@Id
    @GeneratedValue
    private Long id;

    @Temporal(TemporalType.TIMESTAMP)
	private Date createDate;
 
	@Lob
    private byte[] data;
    
	private String owner;
	
	private String filename;
	
	private long size;
	
	
    public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public long getSize() {
		return size;
	}

	public void setSize(long size) {
		this.size = size;
	}

	public Long getId() {
		return id;
	}
    
	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public byte[] getData() {
		return data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Override
	public String toString() {
		return "FileUpload [id=" + id + ", createDate=" + createDate
				+ ", owner=" + owner + ", filename=" + filename + ", size="
				+ size + "]";
	}
	
}

src/main/java/com/cvparse/entity/Language.java
package com.cvparse.entity;

public enum Language {
	java, c, go, javascript, python, ruby, sql
}

src/main/java/com/cvparse/entity/Problem.java
package com.cvparse.entity;

import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Problem {

	@Id
	@GeneratedValue
	private Long id;
	
    @Temporal(TemporalType.TIMESTAMP)
	private Date createDate;
 
    private String problemStatement;
    
	private String owner;
	
	private String name;
	
	private String problemXML;

	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getProblemStatement() {
		return problemStatement;
	}

	public void setProblemStatement(String problemStatement) {
		this.problemStatement = problemStatement;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getProblemXML() {
		return problemXML;
	}

	public void setProblemXML(String problemXML) {
		this.problemXML = problemXML;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "Problem [id=" + id + ", createDate=" + createDate
				+ ", problemStatement=" + problemStatement + ", owner=" + owner
				+ ", name=" + name + ", problemXML=" + problemXML + "]";
	}
}

src/main/java/com/cvparse/entity/ProblemSourceCode.java
package com.cvparse.entity;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class ProblemSourceCode {

	@Id
	@GeneratedValue
	private Long id;
	
    @Temporal(TemporalType.TIMESTAMP)
	private Date createDate;

    private Language language;
    
    private String boilerplate;
    
    private String testcode;
    
    private String owner;
    
    private Long problemId;

	public Long getProblemId() {
		return problemId;
	}

	public void setProblemId(Long problemId) {
		this.problemId = problemId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Language getLanguage() {
		return language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getBoilerplate() {
		return boilerplate;
	}

	public void setBoilerplate(String boilerplate) {
		this.boilerplate = boilerplate;
	}

	public String getTestcode() {
		return testcode;
	}

	public void setTestcode(String testcode) {
		this.testcode = testcode;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Override
	public String toString() {
		return "ProblemSourceCode [id=" + id + ", createDate=" + createDate
				+ ", language=" + language + ", boilerplate=" + boilerplate
				+ ", testcode=" + testcode + ", owner=" + owner
				+ ", problemId=" + problemId + "]";
	}
}

src/main/java/com/cvparse/pojo/Function.java
package com.cvparse.pojo;

import java.util.ArrayList;
import java.util.List;

public class Function {
	private String name;
	private Variable returnValue;
	private List<Variable> parameters;
	
	public void addParameter(Variable parameter) {
		assert parameter != null;
		if (parameters == null) { 
			parameters = new ArrayList<Variable>();
		}
		parameters.add(parameter);
	}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Variable getReturnValue() {
		return returnValue;
	}
	public void setReturnValue(Variable returnValue) {
		this.returnValue = returnValue;
	}
	public List<Variable> getParameters() {
		return parameters;
	}
	public void setParameters(List<Variable> parameters) {
		this.parameters = parameters;
	}
	
	
}

src/main/java/com/cvparse/pojo/VariableType.java
package com.cvparse.pojo;

public enum VariableType {
	INT, LONG, DOUBLE, STRING, BOOLEAN, DATE, ARRAY
}

src/main/java/com/cvparse/TextBean.java
package com.cvparse;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import org.apache.pdfbox.io.RandomAccessBuffer;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.util.PDFTextStripper;
import org.apache.poi.hwpf.HWPFDocument;
import org.apache.poi.hwpf.extractor.WordExtractor;

import com.cvparse.ejb.FileUploadEJB;
import com.cvparse.entity.FileUpload;

@ManagedBean
@RequestScoped
public class TextBean {
	private Logger logger = Logger.getLogger(this.getClass().getName());

    @EJB
    private FileUploadEJB fileUploadEjb;
	
    private long id = 0;

	public String getText() {
		long startTS = System.currentTimeMillis();
		
		if (id == 0) return null;
		
		FileUpload fu = fileUploadEjb.load(id);
		
		if (fu == null) return "could not load id:" + id;
		
		logger.finer(fu.getId() + " created on: " + fu.getCreateDate());
		
		String s = null;
		if (fu.getFilename().endsWith(".pdf")) {
			s = extractPDFText(fu.getData());
		}
		if (fu.getFilename().endsWith(".doc")) {
			s = extractWordText(fu.getData());
		}
		
		logger.info ("extracted text ms: " + (System.currentTimeMillis() - startTS) 
				+ " from file: " + fu.getFilename() + "  of size: " + fu.getSize());
		
		return s;
	}
	
	private String extractPDFText(byte[] pdfBytes) {
		String text = "";
		RandomAccessBuffer tempMemBuffer = new RandomAccessBuffer();
		try {
			PDDocument doc = PDDocument.load(new ByteArrayInputStream(pdfBytes), tempMemBuffer);
			PDFTextStripper sa = new PDFTextStripper();
			text = sa.getText(doc);
		} catch (IOException e) {
			logger.log(Level.SEVERE, "couldn't get text", e);
		}
		return text;
	}

	
	private String extractWordText(byte[] wordBytes) {
		String text = "";
		ByteArrayInputStream finStream = new ByteArrayInputStream(wordBytes);
		
		try {
			HWPFDocument doc = new HWPFDocument(finStream);
			WordExtractor wordExtract = new WordExtractor(doc); 
			String[] dataArray = wordExtract.getParagraphText();
			for (int i = 0; i < dataArray.length; i++) {
				text += ("\n–" + dataArray[i]);
			}
		} catch (IOException e) {
			logger.log(Level.SEVERE, "couldn't get text", e);
		}
		
		return text;
	}
	
    
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

}

src/main/java/com/cvparse/upload/FileUploadBean.java
package com.cvparse.upload;

import java.io.IOException;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.ArrayList;
 
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
 
import org.richfaces.event.FileUploadEvent;
import org.richfaces.model.UploadedFile;

import com.cvparse.ejb.FileUploadEJB;
 
/**
 * http://showcase.richfaces.org/richfaces/component-sample.jsf?demo=fileUpload
 * 
 * FileUpload requires two context-parameter's to be set in web.xml:
 * createTempFiles boolean attribute which defines whether the uploaded 
 *   files are stored in temporary files or available in the listener directly as byte[] 
 *   data (false for this example).
 * maxRequestSize attribute defines max size in bytes of the uploaded files (1000000 for this example).
 * 
 * @author Ilya Shaikovsky
 */
@ManagedBean
@SessionScoped
public class FileUploadBean implements Serializable {
    private ArrayList<UploadedImage> files = new ArrayList<UploadedImage>();
    
    @EJB
    private FileUploadEJB fileUploadEjb;
 
    public void paint(OutputStream stream, Object object) throws IOException {
        stream.write(getFiles().get((Integer) object).getData());
        stream.close();
    }
 
    public void listener(FileUploadEvent event) throws Exception {
        UploadedFile item = event.getUploadedFile();
        UploadedImage file = new UploadedImage();
        file.setLength(item.getData().length);
        file.setName(item.getName());
        file.setData(item.getData());
        
        // store each and every upload to the database... 
        fileUploadEjb.create(item.getData(), item.getName());
        
        files.add(file);
    }
 
    public String clearUploadData() {
        files.clear();
        return null;
    }
 
    public int getSize() {
        if (getFiles().size() > 0) {
            return getFiles().size();
        } else {
            return 0;
        }
    }
 
    public long getTimeStamp() {
        return System.currentTimeMillis();
    }
 
    public ArrayList<UploadedImage> getFiles() {
        return files;
    }
 
    public void setFiles(ArrayList<UploadedImage> files) {
        this.files = files;
    }
}

src/main/webapp/about.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:composition template="index.xhtml">

	<ui:define name="innerbody">

		<div>about</div>

	</ui:define>

</ui:composition>

</html>

src/main/webapp/contact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:composition template="index.xhtml">

	<ui:define name="innerbody">

		<div>contact</div>

	</ui:define>

</ui:composition>

</html>

src/main/webapp/error.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

<body>
	<ui:composition template="/templates/template.xhtml">

		<ui:define name="body">

			<div class="container">
			
			    <p>ooops... some kind of error seems to have occurred</p>
			    <img src="/img/Chains_Atlanticus_Madrid.jpg"></img>

			</div>

		</ui:define>
	</ui:composition>
</body>
</html>

src/main/webapp/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<body>
	<ui:composition>

		<!-- Le styles -->
		<link href="/css/bootstrap.css" rel="stylesheet" />
		<link href="/css/bootstrap-responsive.css" rel="stylesheet" />
	    <link href="/css/bootstrap-formhelpers.css" rel="stylesheet" />
    	<link href="/css/bootstrap-formhelpers-countries.flags.css" rel="stylesheet" />

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
	      <script src="public/js/html5shiv.js"></script>
	    <![endif]-->


		<!--  from http://twitter.github.io/bootstrap/examples/justified-nav.html -->
	<style type="text/css">
      body {
        padding-bottom: 60px;
      }

      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1000px;
      }
      .container > hr {
        margin: 60px 0;
      }

      /* Customize the navbar links to be fill the entire space of the .navbar */
      .navbar .navbar-inner {
        padding: 0;
      }
      .navbar .nav {
        margin: 0;
        display: table;
        width: 100%;
      }
      .navbar .nav li {
        display: table-cell;
        width: 1%;
        float: none;
      }
      .navbar .nav li a {
        font-weight: bold;
        text-align: center;
        border-left: 1px solid rgba(255,255,255,.75);
        border-right: 1px solid rgba(0,0,0,.1);
      }
      .navbar .nav li:first-child a {
        border-left: 0;
        border-radius: 3px 0 0 3px;
      }
      .navbar .nav li:last-child a {
        border-right: 0;
        border-radius: 0 3px 3px 0;
      }
    </style>

    <div class="container">
			<form class="bs-docs-example form-inline">
				<div class="row">
				<div class="span2 offset10 bfh-selectbox bfh-languages" data-language="en_US" 
					data-available="en_US,es_ES,fr_FR,de_DE,it_IT,pl_PL,pt_PT,ru_RU,ja_JP,zh_CN,hi_IN,ar_ZA,tr_TR" data-flags="true">
  					<input type="hidden" value=""></input>
 						<a class="bfh-selectbox-toggle" role="button" data-toggle="bfh-selectbox" href="#">
							<span class="bfh-selectbox-option input-medium" data-option=""></span>
 							<b class="caret"></b>
						</a>
  					<div class="bfh-selectbox-options">
  						<div role="listbox">
						    <ul role="option"></ul>
					  </div>
  				</div>
				</div>
				</div>			
			</form>
			<div class="masthead">
			<div class="navbar">
				<div class="navbar-inner">
					<div class="container">
						<ul class="nav">
							<li class="#{headerBean.homeClass}"><a href="/index.jsf">Home</a></li>
							<li class="#{headerBean.problemClass}"><a href="/problem.jsf">Problem</a></li>
							<li class="#{headerBean.solutionClass}"><a href="/code.jsf">Solution</a></li>
							<li class="#{headerBean.resourcesClass}"><a href="/resources.jsf">Resources</a></li>
						</ul>
					</div>
				</div>
			</div><!-- /.navbar -->
		</div>
	</div>

	</ui:composition>
</body>
</html>

src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:a4j="http://richfaces.org/a4j" xmlns:rich="http://richfaces.org/rich">

<body>
	<ui:composition template="/templates/template.xhtml">

		<ui:define name="body">

    <style type="text/css">
      body {
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>

			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span2">
						<div class="well sidebar-nav">
							<ul class="nav nav-list">
								<li class="nav-header">Home</li>
								<li class="#{homeBean.welcomeClass}"><a href="/index.jsf">Welcome</a></li>
								<li class="#{homeBean.signinClass}"><a href="/signin.jsf">Sign in</a></li>
								<li class="#{homeBean.adminClass}"><a href="/admin/listproblems.jsf">Admin</a></li>
								<li class="nav-header">Company</li>
								<li class="#{homeBean.aboutClass}"><a href="/about.jsf">About</a></li>
								<li class="#{homeBean.jobsClass}"><a href="/jobs.jsf">Jobs</a></li>
								<li class="#{homeBean.partnersClass}"><a href="/partners.jsf">Partners</a></li>
								<li class="#{homeBean.contactClass}"><a href="/contact.jsf">Contact</a></li>
								<li><a href="http://www.google.com">Blog</a></li>
							</ul>
						</div>
						<!--/.well -->
					</div>
					<!--/span-->

					<div class="span8">
						<ui:insert name="innerbody"><img src="/img/duel.jpg"></img></ui:insert>
					</div>
				</div>
			</div>


		</ui:define>
	</ui:composition>
</body>
</html>

src/main/webapp/problem.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

<body>
	<ui:composition template="/templates/template.xhtml">

		<ui:define name="body">

			<div class="container">
			
				<div><h:outputText value="#{problemBean.id}" /> #{msg.courtesy} #{problemBean.url}</div>

				<iframe src="#{problemBean.url}" width="90%" height="500">
					<p>Your browser does not support iframes.</p>
				</iframe>
			</div>

		</ui:define>
	</ui:composition>
</body>
</html>